name: Deploy Gemini API to K3D

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gemini-api:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gemini-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          k3d kubeconfig write mycluster
          export KUBECONFIG=$HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml

      - name: Expose Service
        run: |
          kubectl expose deployment gemini-api --type=LoadBalancer --port=8080

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc

      - name: Test API
        run: |
          curl http://localhost:8080/getanswer
